### PR TITLE
LYP - tier 3 cash upgrades

### PR DESCRIPTION
**Pull request by dr-ishmael**
Also includes the corrected E-Sports speed per #93 .

### CODE REVIEW

**Comment by ricardopetrere** [comment]
Small question:
By including the change from my PR inside your PR, you automatically make our PRs conflict with one another. Why?

**Comment by dr-ishmael** [comment]
If I make mine match yours, how does that make a conflict? I thought conflicts only happened if we changed the same line in *different* ways...

**Comment by ricardopetrere** [comment]
I'm no certified expert on Git (I just learned by using it), but I think that's not how it works.
Even though we make the exact same changes on the exact same lines, both take the same original content as reference to "what has changed in this commit?" / "What has been staged to commit?". I think that's how Git works with Diffs: It stores just the changes, original -> new.
So, in both our commits, it presumes the value on the base fork (Slimmmo/Slimmmo.github.io) was 1400. Once one of the PRs gets merged, the value on the base fork will no longer be 1400, but 700, and that'll give conflict to the other PR, AFAIK.

But let's see what willl happen

**Comment by dr-ishmael** [comment]
I suppose you could just cancel yours and let both changes roll in with
mine?

**Comment by ricardopetrere** [comment]
Yeah, that'll be the easiest way to solve it.
:+1:

**Pull request merged**
