### PR TITLE
Insert Coins to Continue details

### PR DESCRIPTION
**Pull request by dr-ishmael**
I've got everything in except for the angel scale.

### CODE REVIEW

**Comment by 61352151511** [comment]
You're actually about a minute late, but don't worry about angel scale.

**Comment by 61352151511** [comment]
I do see that your values are the same as mine, however I've noticed that my values are causing the calculated price to be incorrect. Say for example Upgrading Fightingfrogs from 2 -> 5, it tells me this will cost 2941.24 however by adding up each cost I did actually spend I get 1069.38, so something is wrong with our values or this event acts different, if you'd like to help me figure this out, it would be appreciated.

**Comment by dr-ishmael** [comment]
Yeah, I didn't see your commit until after I submitted this.

I just figured it out. Our "baseCost" values are actually the cost for the *second* of each investment. So we have to calculate backwards to get the cost of the *first* one:

    $scope.insertcoin.baseCost = [2.5, 5, 7.5, 10, 12.5, 30, 50, 70, 125];

That should fix the calculations.

**Comment by 61352151511** [comment]
My calculations left me with 2.5, 5, 7.5, 10, 12.5, 32.7, 58.3, 70, 125

**Comment by 61352151511** [comment]
That did fix it though, Gonna close this.

**Comment by dr-ishmael** [comment]
The cost of the second Crow&Jack is 90, scale is 3, so 90/3 = 30. For Street Skid, the second costs 175, scale is 3.5, so 175/3.5 = 50.

**Comment by 61352151511** [comment]
You're right, I divided it by the wrong number.

**Comment by dr-ishmael** [comment]
Just noticed you have a typo - investment 8 is "Rad Cap," not "Red Cap."

**Comment by 61352151511** [comment]
Yep, I'm just playing a bit myself to see more cash upgrades and all this will be in the next push in a few seconds. I did notice that myself.

**Comment by dr-ishmael** [comment]
Cool, I'll leave you to it. :)

**Pull request closed without merging**
