### PR TITLE
Live Your Profits!

### PR DESCRIPTION
**Pull request by dr-ishmael**
All investment and unlock data complete. Initial cash/angel upgrades.

### CODE REVIEW

**Comment by ricardopetrere** [comment]
In my game, the angel scale seems to be at 187

**Comment by dr-ishmael** [comment]
I just left a placeholder there for now. I'm seeing around 150, should be able to confirm in a couple minutes.

**Comment by ricardopetrere** [comment]
Correction: 180

**Comment by dr-ishmael** [comment]
Yep, confirmed at 180.

**Pull request merged**
