### PR TITLE
Live Rich and Profit - full data

### PR DESCRIPTION
**Pull request by dr-ishmael**
Here's the complete data for LRaP.

### CODE REVIEW

**Comment by dr-ishmael** [comment]
Tested and fixed all bugs. Should be good to merge this now.

**Comment by dr-ishmael** [comment]
There we go. Ready!

**Comment by Slimmmo** [comment]
Merge conflict. I don't know how to fix it. I tried to overwrite it but something went wrong, idk what happened. If you fix this quickly I'll merge it but I'm about to sleep.

**Comment by dr-ishmael** [comment]
Sorry, I don't know what to do either. You could just select-all from my version of the files and paste into yours, then we can close this pull without merging.

**Comment by Slimmmo** [comment]
OK done, thanks. How did you figure out the numbers? Just from in-game or some other method?

**Comment by dr-ishmael** [comment]
From in-game. I had nearly cleared all of the cash upgrades last night before I decided to do this, so I was able to get them all fairly quickly. The toughest part was the angel multiplier - I hadn't really understood how that worked before now - but once I had that it was relatively easy to derive the rest.

**Comment by dr-ishmael** [comment]
Crap, just noticed that I missed an unlock on Space Buddies. There are *2* unlocks you get simultaneously at 150, one is x2 profit and one is x2 speed. Just need to modify line 1337 in main.js:

    $scope.liverich.unlocks[8] = [[1, [16, 5]], [25, [17, 2]], [75, [17, 2]], [150, [17, 2]], [150, [16, 2]]];

**Comment by Slimmmo** [comment]
Thanks, fixed. Will close this now but feel free to keep posting if there's more stuff.

**Comment by dr-ishmael** [comment]
Awesome. Glad I could contribute!

**Pull request closed without merging**
