### PR TITLE
Added Make It Rain

### PR DESCRIPTION
**Pull request by metoxys**
Enabled the Make It Rain event tab, added the investments, added all the milestones, added two tiers of cash upgrades and ~1.5 tiers of angel upgrades.

WARNING! Angel investor variable thingy is a placeholder.
WARNING! Data for Yucky Charms is less accurate than the other data I have

### CODE REVIEW

**Comment by 61352151511** [comment]
You might want to squash this to one commit if possible.

**Comment by Slimmmo** [comment]
Your angel upgrades are missing decimal points. e.g [8e+7, [4, 9], false, false] should be [8.7e+7, [4, 9], false, false]

**Comment by Slimmmo** [comment]
Also, the last rain.unlocks[9] should be [18, 2] not [19, 2]. Also, if you could change angelScale to 45 (it's not right but it's close) then I'll check the angels and merge it.

**Comment by Slimmmo** [comment]
Just saw your PM on Reddit. I'll merge now and fix them myself. Thanks.

**Pull request merged**
