### PR TITLE
Decimal places on AI Bonus and Badges group (in progress)

### PR DESCRIPTION
**Pull request by ricardopetrere**
Update 4.0 created some Cash Upgrades that add AI effectiveness by 0.3% and made special badges affect specific businesses (the "Badges" group is still a work in progress, I just added the group to the site)

### CODE REVIEW

**Comment by 61352151511** [comment]
The Angel Investor Bonus doesn't need a step of 0.1 because the only way for it to have a decimal would be from cash upgrades so there's no reason to input a custom one. Please finish badges and input the new upgrades for this to be accepted or ill work on fixing this up soon.

**Comment by ricardopetrere** [comment]
Well... From everything that composes this Calculator (HTML, AngularJS, Bootstrap), HTML was the only one I was sure of what I was doing (never learned the rest), that's why there's only a blank "Badges" group.
But OK, I'll do all the rest, then :+1:

**Comment by ricardopetrere** [comment]
OK, I've done all I could (I'm still at octogintillion on Earth, so I can't see some upgrades)
Hope it's OK!

**Comment by dr-ishmael** [comment]
I posted all the cash upgrades to reddit: https://www.reddit.com/r/AdventureCapitalist/comments/4tgfq8/new_update_on_ios_in_preparation_for_the_july/d5hnpn0?st=iqwska9j&sh=dbe926fb

There are also some changes to angel upgrades, I covered those in a response to that comment.

**Comment by ricardopetrere** [comment]
Oh, it seems we're both at the same upgrades
But I think your comment (at least the one in the link you passed) was deleted

**Comment by dr-ishmael** [comment]
I don't know what you mean. That's the permalink to my comment where I listed all the new cash upgrades for AI Effectiveness (The. End. Times. Are. Upon. Us...) and All Profit (Earth. The Final Frontier...).

It shows my reply to that comment where I described the changes to angel upgrades. But here's the permalink to that one, just in case: https://www.reddit.com/r/AdventureCapitalist/comments/4tgfq8/new_update_on_ios_in_preparation_for_the_july/d5ho0je

**Pull request merged**
