### PR TITLE
Platinum Boost Update

### PR DESCRIPTION
**Pull request by 61352151511**

### CODE REVIEW

**Comment by Slimmmo** [comment]
Why was this done? Is it ever not 17.77?

**Comment by jaysoncopes** [comment]
@Slimmmo they just updated to allow a Platinum Boost Upgrade to 77.77. 

http://i.imgur.com/Helnzp7h.jpg

**Comment by 61352151511** [comment]
And it goes on to 777.77 and 7777.77 I read that that's the max

**Comment by jaysoncopes** [comment]
@61352151511 It seems like maybe it would be better implementation for the user to make those incremental upgrades automatic instead of making them type in the multiplier. That's just my initial thoughts, though.

**Comment by 61352151511** [comment]
Yes, yes. I at first saw the update and thought it would just go on forever but now knowing there's a max (according to users on reddit) perhaps it could just be a drop down or something where they select which bonus they have. I can change this tomorrow morning if it's preferred

**Comment by jaysoncopes** [comment]
That sounds nice. I'll see if I have time here in a bit, too.

**Comment by 61352151511** [comment]
So because I always have issues with dropdown menus, and it doesn't really fit with what's on the site now. I've changed it to use checkboxes like the suits. Although this doesn't look that nice, it functions how it should. 

ss 2016-04-26 at 08 26 12

**Comment by Ragowit** [comment]
Would love to see this one merged. @Slimmmo

**Pull request merged**
